### ISSUE TITLE
Bug on [IgnoreParent]

### ISSUE THREAD

**Issue by jinsediaoying** [arimger/Unity-Editor-Toolbox#19]
```
public class Test : MonoBehaviour
{
	[IgnoreParent]
	public A a;

	public List<A> aList;
}

[Serializable]
public class A
{
	public int x;
}
```

![RYKEFT8SA3K@AV8D1IR3AG](https://user-images.githubusercontent.com/25916527/124350813-61f2bd00-dc29-11eb-9251-91ece829ff36.png)

**Comment by jinsediaoying** [comment]
```
public class Test : MonoBehaviour
{
	//public A a;

	[IgnoreParent]
	public List<A> aList;
}

[Serializable]
public class A
{
	public int x;
}
```

![7D(%W%W7{TAIO2E9JIA@HUE](https://user-images.githubusercontent.com/25916527/124350879-beee7300-dc29-11eb-9b68-4e4ce0ba59fa.png)

**Comment by arimger** [comment]
It's by design. [IgnoreParent] targets only single properties and is not available for lists, applying it to the list/array property will affect only elements, in the same way works [InLineEditor]. I don't really think skipping the list's label in the Inspector will give you any benefit but if you really want I can share code with you and then you will be able to apply it to your codebase.

**Comment by jinsediaoying** [comment]
The actual bug is that [IgnoreParent] will casue the rest properties being draw multiple times.

And remove the list items' foldout is actually the thing I want.

**Comment by arimger** [comment]
Ach, sorry, I'm blind!

**Comment by arimger** [comment]
A potential fix is available on the development branch, can you check if everything works as expected?

**Comment by jinsediaoying** [comment]
Every thing looks good..
