### ISSUE TITLE
[Feature Request] Nested Reference Picker

### ISSUE THREAD

**Issue by Kamatis** [arimger/Unity-Editor-Toolbox#47]
Currently, when you put a `ReferencePicker` attribute inside another `ReferencePicker` member, the child just shows the label without the `ReferencePicker`. I suggest having the `ReferencePicker` go down for multiple child levels.

**Comment by arimger** [comment]
Hello, thank you for the issue. 

This is currently on my TODO list because [SerializeReference]-based properties don't support ToolboxAttributes at all. It's related to the obsolete logic of retrieving **FieldInfo** of such field (targeted type is serialized, not stored in the field). Anyway, for sure I will change it.

**Comment by arimger** [comment]
Should be fixed in https://github.com/arimger/Unity-Editor-Toolbox/pull/48.

If you encounter any other problem/bug related to [SerializeReference] usage please create another issue.
