### ISSUE TITLE
Trying to render ScriptedImporter with ToolboxEditor

### ISSUE THREAD

**Issue by zzmingo** [arimger/Unity-Editor-Toolbox#59]
Hi, 

I am trying to render ScriptedImporter with ToolboxEditor, but not found a way.
So I copy most code of ToolboxEditor, but `ToolboxEditorGui.DrawToolboxProperty(property)` seems doesn't draw anything in this case.

Any sugguestions?

**Comment by arimger** [comment]
Hello,

it's probably related to how ScriptedImporterEditor & AssetImporterEditor are responsible for drawing ScriptableObjects. It's my first guess but you need to mimic the [OnInspectorGUI method](https://github.com/Unity-Technologies/UnityCsReference/blob/332310b494c5416cdae6c1209dbae7cfa6847c8d/Modules/AssetPipelineEditor/ImportSettings/AssetImporterEditor.cs#L427).

So basically:
```
        public override sealed void OnInspectorGUI()
        {
            try
            {
                OnBeginToolboxEditor?.Invoke(this);
                DrawCustomInspector(serializedObject);
                if (extraDataType != null)
                {
                   DrawCustomInspector(extraDataSerializedObject);
                }

                ApplyRevertGUI();
            }
            catch (Exception)
            {
                OnBreakToolboxEditor?.Invoke(this);
                throw;
            }
            finally
            {
                OnCloseToolboxEditor?.Invoke(this);
            }
        }
```

You need to refactor DrawCustomInspector a bit because currently, this method is using the **serializedObject** field instead of an argument. I can look at it in a few days.

**Comment by zzmingo** [comment]
@arimger thanks for your reply.

This is my code about DrawCustomInspector,  it's works with `EditorGUILayout.PropertyField(property)` but nothing drawing on inspector with `ToolboxEditorGui.DrawToolboxProperty(property)`

```C#
    public virtual void DrawCustomInspector()
    {
      
      if (true) // ToolboxDrawerModule.ToolboxDrawersAllowed)
      {
        serializedObject.Update();
    
        var property = serializedObject.GetIterator();
        while (property.NextVisible(enterChildren: false))
        {
          EditorGUILayout.PropertyField(property);                      // works
          // ToolboxEditorGui.DrawToolboxProperty(property);   // no fields drawing on inspector
        }
        serializedObject.ApplyModifiedProperties();
        return;
      }
      
    }
```

**Comment by zzmingo** [comment]
Good job, I will try the PR or the next release.
No warnings were found in the prev version.

**Comment by zzmingo** [comment]
Tried the PR, and it works.
Thank you very much.
